apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  db_name: Y2Fwcm92ZXI=        # caprover base64
  db_user: Y2Fwcm92ZXI=        # caprover base64
  db_password: cm9vdA==        # root base64
  mysq_root_password: cm9vdA==  # root base64