apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-caprover
  name: mysql-caprover
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-caprover
status:
  loadBalancer: {}